version: '2'

services:

  mysql-server:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#      MYSQL_USER: myweb
#      MYSQL_PASSWORD: secret
    ports:
     - ${MYSQL_PORT}
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  apache-server:
    image: apps4net/laravel-apache:1.1
    ports:
      - ${APP_PORT}
#      - "443:443"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./www/laradock:/var/www/html
      - ./docker/apache/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - mysql-server